version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
  web:
    build: .
    command: python ./core/manage.py runserver 0.0.0.0:9900
    volumes:
      - .:/code
    ports:
      - "9900:9900"
    environment:
      POSTGRES_NAME: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      REDIS_PASSWORD: "${REDIS_PASS}"
      UBERDUCKKEY: "${UBERDUCKKEY}"
      UBERDUCKSEC: "${UBERDUCKSEC}"
    depends_on:
      - db
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
